[[books]]
name = "Мастер-класс. Совершенный код."
authors = ["Макконнелл Скотт"]
price = 1419
rating = 9.8
description = "Более 10 лет первое издание этой книги считалось одним из лучших практических руководств по программированию. Сейчас эта книга полностью обновлена с учетом современных тенденций и технологий и дополнена сотнями новых примеров, иллюстрирующих искусство и науку программирования. Опираясь на академические исследования, с одной стороны, и практический опыт коммерческих разработок ПО - с другой, автор синтезировал из самых эффективных методик и наиболее эффективных принципов ясное прагматичное руководство. Каков бы ни был ваш профессиональный уровень, с какими бы средствами разработками вы ни работали, какова бы ни была сложность вашего проекта, в этой книге вы найдете нужную информацию, она заставит вас размышлять и поможет создать совершенный код. Изложенные в книге методики и стратегии помогут вам:проектировать с минимальной сложностью и максимальной продуктивностью извлекать выгоду из групповой разработки применять методики защитного программирования, позволяющие избежать ошибок совершенствовать свой код применять методики конструирования, наиболее подходящие для вашего проекта быстро и эффективно производить отладку своевременно и быстро обнаруживать критические проблемы проекта обеспечивать качество на всех стадиях проекта."
code = 0
publisher = "БХВ-Петербург"
year = 2017
pages = 896
isbn = "978-5-99543805-1-8"

[[books]]
name = "Грокаем алгоритмы. Иллюстрированное пособие для программистов и любопытствующих"
authors = ["Адитья Бхаргава"]
price = 959
rating = 9.4
description = "Алгоритмы — это всего лишь пошаговые алгоритмы решения задач, и большинство таких задач уже были кем-то решены, протестированы и проверены. Можно, конечно, погрузиться в глубокую философию гениального Кнута, изучить многостраничные фолианты с доказательствами и обоснованиями, но хотите ли вы тратить на это свое время? Откройте великолепно иллюстрированную книгу, и вы сразу поймете, что алгоритмы — это просто. А грокать алгоритмы — это веселое и увлекательное занятие."
code = 1
publisher = "Питер"
year = 2017
pages = 288
isbn = "978-5-4461-0923-4"

