[[books]]
name = "Мастер-класс. Совершенный код."
authors = ["Макконнелл Скотт"]
price = 1419
rating = 9.8
description = "Более 10 лет первое издание этой книги считалось одним из лучших практических руководств по программированию. Сейчас эта книга полностью обновлена с учетом современных тенденций и технологий и дополнена сотнями новых примеров, иллюстрирующих искусство и науку программирования. Опираясь на академические исследования, с одной стороны, и практический опыт коммерческих разработок ПО - с другой, автор синтезировал из самых эффективных методик и наиболее эффективных принципов ясное прагматичное руководство. Каков бы ни был ваш профессиональный уровень, с какими бы средствами разработками вы ни работали, какова бы ни была сложность вашего проекта, в этой книге вы найдете нужную информацию, она заставит вас размышлять и поможет создать совершенный код. Изложенные в книге методики и стратегии помогут вам:проектировать с минимальной сложностью и максимальной продуктивностью извлекать выгоду из групповой разработки применять методики защитного программирования, позволяющие избежать ошибок совершенствовать свой код применять методики конструирования, наиболее подходящие для вашего проекта быстро и эффективно производить отладку своевременно и быстро обнаруживать критические проблемы проекта обеспечивать качество на всех стадиях проекта."
code = 0
publisher = "БХВ-Петербург"
year = 2017
pages = 896
isbn = "978-5-99543805-1-8"

[[books]]
name = "Грокаем алгоритмы. Иллюстрированное пособие для программистов и любопытствующих"
authors = ["Адитья Бхаргава"]
price = 959
rating = 9.4
description = "Алгоритмы — это всего лишь пошаговые алгоритмы решения задач, и большинство таких задач уже были кем-то решены, протестированы и проверены. Можно, конечно, погрузиться в глубокую философию гениального Кнута, изучить многостраничные фолианты с доказательствами и обоснованиями, но хотите ли вы тратить на это свое время? Откройте великолепно иллюстрированную книгу, и вы сразу поймете, что алгоритмы — это просто. А грокать алгоритмы — это веселое и увлекательное занятие."
code = 1
publisher = "Питер"
year = 2017
pages = 288
isbn = "978-5-4461-0923-4"

[[books]]
name = "Изучаем Arduino: инструменты и методы технического волшебства"
authors = ["Блум, Джереми"]
price = 560
rating = 10.0
description = "Книга посвящена проектированию электронных устройств на основе микроконтроллерной платформы Arduino. Приведены основные сведения об аппаратном и программном обеспечении Arduino. Изложены принципы программирования в интегрированной среде Arduino IDE. Показано, как анализировать электрические схемы, читать технические описания, выбирать подходящие детали для собственных проектов. Приведены примеры использования и описание различных датчиков, электродвигателей, сервоприводов, индикаторов, проводных и беспроводных интерфейсов передачи данных. В каждой главе перечислены используемые комплектующие, приведены монтажные схемы, подробно описаны листинги программ. Имеются ссылки на сайт информационной поддержки книги. Материал ориентирован на применение несложных и недорогих комплектующих для экспериментов в домашних условиях."
code = 9
publisher = "БВХ-Петербург"
year = 2017
pages = 336
isbn = "978-5-9775-3585-4"

[[books]]
name = "Сам себе программист. Как научиться программировать и устроиться в Ebay?"
authors = ["Альтхофф"]
price = 959
rating = 8.5
description = "Автор книги всего за год научился программировать, что само по себе немало. Однако Кори Альтхофф пошел дальше, и научившись программировать, он устроился разработчиком в одну из самых серьезных современных IT компаний - Ebay. Как ему удалось? Читайте эту книгу, изучайте программирование на языке Python по уникальной авторской методике - вам это тоже по силам!"
code = 7
publisher = "Эксмо"
year = 2021
pages = 208
isbn = "978-5-04-090834-9"